#!/bin/sh
# simple script to build program distribution

# delete the directory with old distribution
rm -rv dist/archon_migration

# create new directory
mkdir -p dist/archon_migration
mkdir -p dist/archon_migration/lib
mkdir -p dist/archon_migration/logs

# copy the needed files
cp -v out/artifacts/archon_migration_jar/* dist/archon_migration/lib
cp -v run.* dist/archon_migration

# create a zip of the source code
cd dist

zip -vr archon_migration.zip archon_migration -x "*.svn*" "*.DS_Store*"
